#!/bin/sh

mkdir /proc
mount -t proc none /proc
mkdir /sys
mount -t sysfs none /sys
touch /dev/null
ls -d /etc/modules/* | xargs /sbin/insmod # load modules
/scripts/setup-network.sh # setup network
insmod /data/dist_comm.ko
mdev -d
cat <<!


Boot took $(cut -d' ' -f1 /proc/uptime) seconds

        _       _     __ _
  /\/\ (_)_ __ (_)   / /(_)_ __  _   ___  __
 /    \| | '_ \| |  / / | | '_ \| | | \ \/ /
/ /\/\ \ | | | | | / /__| | | | | |_| |>  <
\/    \/_|_| |_|_| \____/_|_| |_|\__,_/_/\_\


Welcome to mini_linux


!

cd /data
exec /bin/sh
