#ifndef LIB_DEV_H
#define LIB_DEV_H

#define MANAGER_CMD_MAGIC_NUM 100
#define MANAGER_REG_INTERFACE_CMD _IOW(MANAGER_CMD_MAGIC_NUM, 1, char *)
#define MANAGER_REMOVE_INTERFACE_CMD _IOW(MANAGER_CMD_MAGIC_NUM, 3, int)
#define MANAGER_TEST_EXECUTE_REMOTE_CMD _IOW(MANAGER_CMD_MAGIC_NUM, 4, char*)

#define MANAGER_DEVICE_FILE_NAME "/dev/dcm"

#define PEER_CMD_MAGIC_NUM 101
#define PEER_EXEC_INTERFACE_CMD _IOW(PEER_CMD_MAGIC_NUM, 1, struct interface *)

#define EIFNOTFOUND 50000

#endif
